### ISSUE TITLE
App crash every time.

### ISSUE THREAD

**Issue by waleedkalyar** [susonthapa/curved-bottom-navigation#15]
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.jeuxdevelopers.prayerwatch/com.jeuxdevelopers.prayerwatch.activities.main.MainActivity}: java.lang.ClassCastException: **android.graphics.drawable.VectorDrawable cannot be cast to android.graphics.drawable.AnimatedVectorDrawable**
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2665)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6119)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
     Caused by: java.lang.ClassCastException: android.graphics.drawable.VectorDrawable cannot be cast to android.graphics.drawable.AnimatedVectorDrawable
        at androidx.vectordrawable.graphics.drawable.AnimatedVectorDrawableCompat.start(AnimatedVectorDrawableCompat.java:711)
        at np.com.susanthapa.curved_bottom_navigation.CurvedBottomNavigationView.setupInitialAVD(CurvedBottomNavigationView.kt:311)
        at np.com.susanthapa.curved_bottom_navigation.CurvedBottomNavigationView.setMenuItems(CurvedBottomNavigationView.kt:305)
        at np.com.susanthapa.curved_bottom_navigation.CurvedBottomNavigationView.setMenuItems$default(CurvedBottomNavigationView.kt:286)
        at com.jeuxdevelopers.prayerwatch.activities.main.MainActivity.setBottomNavMenu(MainActivity.kt:42)
        at com.jeuxdevelopers.prayerwatch.activities.main.MainActivity.init(MainActivity.kt:20)
        at com.jeuxdevelopers.prayerwatch.activities.main.MainActivity.onCreate(MainActivity.kt:16)
        at android.app.Activity.performCreate(Activity.java:6747)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2618)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726) 
        at android.app.ActivityThread.-wrap12(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.app.ActivityThread.main(ActivityThread.java:6119) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

**Comment by waleedkalyar** [comment]
Your Library is awesome just fix the above exception The problem in your library class 
**AnimatedVectorDrawableCompat** class
line 711 ->   ((AnimatedVectorDrawable) mDelegateDrawable).start();
Issue -> java.lang.ClassCastException: android.graphics.drawable.VectorDrawable cannot be cast to android.graphics.drawable.AnimatedVectorDrawable

**Comment by susonthapa** [comment]
As the exception states, you are passing VectorDrawable instead of AnimatedVectorDrawable. This library doesn't support VectorDrawable but you can just convert VectorDrawable into AnimatedVectorDrawable using tools like https://shapeshifter.design/

**Comment by waleedkalyar** [comment]
Thanks I understood!
