### ISSUE TITLE
Unable to start activity ComponentInfo{com.ccninfotech.cybervpnpro/com.ccninfotech.cybervpnpro.ui.MainActivity}: java.lang.UnsupportedOperationException: Sorting went bad, the start event should always be at index 0

### ISSUE THREAD

**Issue by Emranul-Islam** [susonthapa/curved-bottom-navigation#31]
Caused by java.lang.UnsupportedOperationException: Sorting went bad, the start event should always be at index 0
       at android.animation.AnimatorSet.sortAnimationEvents(AnimatorSet.java:1638)
       at android.animation.AnimatorSet.createDependencyGraph(AnimatorSet.java:1534)
       at android.animation.AnimatorSet.initAnimation(AnimatorSet.java:700)
       at android.animation.AnimatorSet.start(AnimatorSet.java:719)
       at android.animation.AnimatorSet.start(AnimatorSet.java:684)
       at np.com.susanthapa.curved_bottom_navigation.BottomNavItemView.startIntermediateAnimation(BottomNavItemView.kt:58)
       at np.com.susanthapa.curved_bottom_navigation.CurvedBottomNavigationView.getBezierCurveAnimation$lambda-11$lambda-10(CurvedBottomNavigationView.java:609)
       at android.animation.ValueAnimator.animateValue(ValueAnimator.java:1653)
       at android.animation.ValueAnimator.setCurrentFraction(ValueAnimator.java:775)
       at android.animation.ValueAnimator.setCurrentPlayTime(ValueAnimator.java:738)
       at android.animation.ValueAnimator.start(ValueAnimator.java:1170)
       at android.animation.ValueAnimator.start(ValueAnimator.java:1189)
       at android.animation.ValueAnimator.startWithoutPulsing(ValueAnimator.java:1182)
       at android.animation.AnimatorSet.handleAnimationEvents(AnimatorSet.java:1149)
       at android.animation.AnimatorSet.startAnimation(AnimatorSet.java:1234)
       at android.animation.AnimatorSet.start(AnimatorSet.java:729)
       at android.animation.AnimatorSet.start(AnimatorSet.java:684)
       at np.com.susanthapa.curved_bottom_navigation.CurvedBottomNavigationView.animateItemSelection(CurvedBottomNavigationView.kt:534)
       at np.com.susanthapa.curved_bottom_navigation.CurvedBottomNavigationView.onMenuItemClick(CurvedBottomNavigationView.kt:490)
       at np.com.susanthapa.curved_bottom_navigation.CurvedBottomNavigationView.setupWithNavController$lambda-6(CurvedBottomNavigationView.kt:387)
       at androidx.navigation.NavController.addOnDestinationChangedListener(NavController.kt:402)
       at np.com.susanthapa.curved_bottom_navigation.CurvedBottomNavigationView.setupWithNavController(CurvedBottomNavigationView.kt:378)
       at com.ccninfotech.cybervpnpro.ui.MainActivity.handleBottomNavigation(MainActivity.kt:160)
       at com.ccninfotech.cybervpnpro.ui.MainActivity.onCreate(MainActivity.kt:85)
       at android.app.Activity.performCreate(Activity.java:8305)
       at android.app.Activity.performCreate(Activity.java:8284)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1417)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3626)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3782)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:201)
       at android.os.Looper.loop(Looper.java:288)
       at android.app.ActivityThread.main(ActivityThread.java:7872)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)

**Comment by susonthapa** [comment]
Similar to #12
